# Harmony Jekyll theme general configurations

# Base URL
baseurl:

# Site live URL
url: http://alioygur.github.io

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Ali OYGUR
  # Little description about your site
  description: Halka açık not defterim.
  meta_description:
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Ali OYGUR
    email: alioygur@gmail.com
    url: http://alioygur.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-6562504-14

  # Profile links, leave blank to ignore
  social:
    github: alioygur
    twitter: alioygur
    facebook:
    gplus:
    dribble:
    pinterest:
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
